import React from 'react';

export default function Terms() {
  return (
    <div className="page page-mid page-enter prose">
      <h2 className="page-title">Terms of Service</h2>
      <p className="tiny faint mono">Last updated: January 2026</p>

      <h2>1. What FitAI is (and isn't)</h2>
      <p>
        FitAI provides AI-assisted fitness and nutrition guidance based on the information you give
        it. It is <strong>not medical advice</strong>, and it is not a substitute for a physician,
        physiotherapist, registered dietitian, or other qualified professional. Consult a doctor
        before starting any exercise or nutrition program, especially if you have a medical
        condition, are pregnant, or are recovering from injury. Stop any exercise that causes pain.
      </p>

      <h2>2. Your account</h2>
      <p>
        You must be at least 13 years old. You're responsible for keeping your credentials secure
        and for the accuracy of the information you enter — plans, targets, and pace calculations
        are only as good as the data behind them.
      </p>

      <h2>3. Acceptable use</h2>
      <p>
        Don't abuse the service: no attempting to breach security, scrape other users' data,
        overload the API, or use the AI coach to generate content unrelated to fitness. We may
        rate-limit or suspend accounts that do.
      </p>

      <h2>4. AI-generated content</h2>
      <p>
        Coaching answers, plan suggestions, review narratives, and food-photo estimates are
        generated by AI models and validated automatically, but they can still be wrong. Numeric
        targets (calories, pace, progression) are computed from standard formulas over your data.
        Use judgment; when the app itself flags low confidence or recommends a professional, take
        that seriously.
      </p>

      <h2>5. Your content and data</h2>
      <p>
        You own the data you log. We process it to run the service as described in the{' '}
        <a href="/privacy">Privacy Policy</a>. You can stop using the service at any time.
      </p>

      <h2>6. Availability and changes</h2>
      <p>
        The service is provided "as is", without warranties of any kind. Features may change,
        improve, or be withdrawn. We work hard on reliability (the app degrades gracefully when AI
        providers are down) but do not guarantee uninterrupted availability.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, FitAI is not liable for injuries, health outcomes,
        or indirect damages arising from use of the service. Your sole remedy for dissatisfaction
        is to stop using it.
      </p>

      <h2>8. Contact</h2>
      <p>Questions about these terms: gsaikrishnad@gmail.com.</p>
    </div>
  );
}
