import React from 'react';

// Legal is the most editorial surface in the app: a measure, a rule between
// clauses, and nothing else. The clause number moves out of the heading into
// the mono label column so all eight headings start on one vertical.
const CLAUSE = {
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 2.5rem) minmax(0, 1fr)',
  gap: '0 var(--s4)',
  // baseline, not start: the clause number must sit on the heading's own
  // baseline, and a hand-tuned line-height would drift the moment the
  // heading size changed.
  alignItems: 'baseline',
  borderTop: '1px solid var(--border)',
  padding: 'var(--s5) 0 0',
  marginTop: 'var(--s5)',
};
const INDEX = { fontSize: 'var(--t-label)', letterSpacing: '0.14em', color: 'var(--faint)' };

const CLAUSES = [
  {
    heading: "What FitAI is (and isn't)",
    body: (
      <>
        FitAI provides AI-assisted fitness and nutrition guidance based on the information you give
        it. It is <strong>not medical advice</strong>, and it is not a substitute for a physician,
        physiotherapist, registered dietitian, or other qualified professional. Consult a doctor
        before starting any exercise or nutrition program, especially if you have a medical
        condition, are pregnant, or are recovering from injury. Stop any exercise that causes pain.
      </>
    ),
  },
  {
    heading: 'Your account',
    body: (
      <>
        You must be at least 13 years old. You're responsible for keeping your credentials secure
        and for the accuracy of the information you enter — plans, targets, and pace calculations
        are only as good as the data behind them.
      </>
    ),
  },
  {
    heading: 'Acceptable use',
    body: (
      <>
        Don't abuse the service: no attempting to breach security, scrape other users' data,
        overload the API, or use the AI coach to generate content unrelated to fitness. We may
        rate-limit or suspend accounts that do.
      </>
    ),
  },
  {
    heading: 'AI-generated content',
    body: (
      <>
        Coaching answers, plan suggestions, daily briefings (including pace estimates), and
        food-photo estimates are generated by AI models and validated automatically, but they can
        still be wrong. Calorie and safety targets are computed from standard formulas over your
        data. Use judgment; when the app itself flags low confidence or recommends a professional,
        take that seriously.
      </>
    ),
  },
  {
    heading: 'Your content and data',
    body: (
      <>
        You own the data you log. We process it to run the service as described in the{' '}
        <a href="/privacy">Privacy Policy</a>. You can stop using the service at any time.
      </>
    ),
  },
  {
    heading: 'Availability and changes',
    body: (
      <>
        The service is provided "as is", without warranties of any kind. Features may change,
        improve, or be withdrawn. We work hard on reliability (the app degrades gracefully when AI
        providers are down) but do not guarantee uninterrupted availability.
      </>
    ),
  },
  {
    heading: 'Limitation of liability',
    body: (
      <>
        To the maximum extent permitted by law, FitAI is not liable for injuries, health outcomes,
        or indirect damages arising from use of the service. Your sole remedy for dissatisfaction
        is to stop using it.
      </>
    ),
  },
  {
    heading: 'Contact',
    body: <>Questions about these terms: gsaikrishnad@gmail.com.</>,
  },
];

export default function Terms() {
  return (
    <div className="page page-mid page-enter">
      <h1 className="page-title">Terms of Service</h1>
      {/* Kept OUT of .prose deliberately: as a direct child paragraph it was
          being caught by the standfirst rule and set at display size. */}
      <p className="tiny faint mono" style={{ margin: 0 }}>Last updated: January 2026</p>

      <div className="prose">
        {CLAUSES.map((c, i) => (
          <section key={c.heading} style={CLAUSE}>
            <span className="mono" aria-hidden="true" style={INDEX}>{i + 1}.</span>
            <div style={{ minWidth: 0 }}>
              <h2 style={{ marginTop: 0, marginBottom: 'var(--s3)' }}>{c.heading}</h2>
              <p style={{ margin: 0 }}>{c.body}</p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
